version: '3.7'

services:
  database:
    image: mongo:4.2
    container_name: corona-map-api-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
